/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package springworkspace;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.Setter;

@Getter
@Setter
// @NoArgsConstructor // 빈 생성자 만들어 짐
@AllArgsConstructor // 생성자를 자동으로 만들어 줌
@RequiredArgsConstructor // final로 지정돼 있는 곳에만 생성자 만들어줌
@Builder
class Person {
    private final String name; // final은 초기화를 반드시 해야 함 - Required
    private int age;
}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Person person = new Person("홍길동", 20); // 인스턴스 만드는 것
        person = new Person("고길동"); // 빈 생성자가 만들어져서 사용가능해 짐 - @NoArgs
        
        // 어떤 곳에 있는지 알 수 있음
        person = Person.builder().name("홍길동").age(20).build();
    }
}     